// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.DataContext;

namespace WebApp.Migrations
{
    [DbContext(typeof(EfDbContext))]
    [Migration("20211215105634_datecolincallback")]
    partial class datecolincallback
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Models.Entities.CallBackHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("allDataInJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("billing_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("charging_token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("consumer_identity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("merchant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("operation_reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("payment_transaction_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("service_ends_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("service_starts_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("subscription_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subscription_uuid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unsubscribe_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uuid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CallBackHistory");
                });

            modelBuilder.Entity("Models.Entities.Payment_History", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MSISDN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("billing_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("operation_reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("payment_transaction_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("service_ends_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("service_starts_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("subscription_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Payment_History");
                });

            modelBuilder.Entity("Models.Entities.Payment_Initiate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MSISDN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operation_Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service_MapID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updatedby")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Payment_Initiate");
                });

            modelBuilder.Entity("Models.Entities.Service_Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Channel_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceOrAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ServiceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Service_Map");
                });

            modelBuilder.Entity("Models.Entities.Subscription_Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Last_Update")
                        .HasColumnType("datetime2");

                    b.Property<string>("MSISDN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operation_reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Reg_Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Reg_Status")
                        .HasColumnType("bit");

                    b.Property<string>("ServiceMap_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subscription_uuid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subscription_Status");
                });

            modelBuilder.Entity("Models.Entities.UnSubscripeCallBackHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("allDataInJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("billing_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("charging_token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("consumer_identity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("merchant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("operation_reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("service_ends_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("service_starts_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("subscription_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subscription_uuid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("timestamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unsubscribe_url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnSubscripeCallBackHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
